# Generated by Django 5.1.3 on 2025-02-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
